#!/usr/bin/env bash

tag_fenix_android() {
  if [ "$#" = 0 ]; then
    echo "ffver \"build + num\" tbseries rebase"
    return 0
  fi
  FFVER=$1
  if [ -z "${FFVER}" ]; then
    echo "Specify firefox version (68.2.0)"
    return 1
  fi
  BUILD=$2
  if [ -z "${BUILD}" ]; then
    echo "Specify build number (build1)"
    return 1
  fi
  TBSERIES=$3
  if [ -z "${TBSERIES}" ]; then
    echo "Specify Tor Browser series (ex. 9.0)"
    return 1
  fi
  REBASE=$4
  if [ -z "${REBASE}" ]; then
    echo "Rebase number (ex. 1)"
    return 1
  fi
  REBASE_COMMENT=
  if [ "${REBASE}" -ne "1" ]; then
    REBASE_COMMENT=" (rebase ${REBASE})"
  fi

  CHANNEL=stable
  if `echo ${TBSERIES} | grep -q 11\.5`; then
    CHANNEL=alpha
  fi

  git tag -s tor-browser-${FFVER}-${TBSERIES}-${REBASE}-${BUILD} -m "Tagging ${BUILD}${REBASE_COMMENT} for ${FFVER}-based ${CHANNEL}"
}

tag_mozac() {
  if [ "$#" = 0 ]; then
    echo "mozacver \"build + num\" tbseries rebase"
    return 0
  fi
  MOZACVER=$1
  if [ -z "${MOZACVER}" ]; then
    echo "Specify mozac version (68.2.0)"
    return 1
  fi
  BUILD=$2
  if [ -z "${BUILD}" ]; then
    echo "Specify build number (build1)"
    return 1
  fi
  TBSERIES=$3
  if [ -z "${TBSERIES}" ]; then
    echo "Specify Tor Browser series (ex. 9.0)"
    return 1
  fi
  REBASE=$4
  if [ -z "${REBASE}" ]; then
    echo "Rebase number (ex. 1)"
    return 1
  fi
  REBASE_COMMENT=
  if [ "${REBASE}" -ne "1" ]; then
    REBASE_COMMENT=" (rebase ${REBASE})"
  fi

  CHANNEL=stable
  if `echo ${TBSERIES} | grep -q 11\.0`; then
    CHANNEL=alpha
  fi

  git tag -s android-components-${MOZACVER}-${TBSERIES}-${REBASE}-${BUILD} -m "Tagging ${BUILD}${REBASE_COMMENT} for ${MOZACVER}-based ${CHANNEL}"
}

tag_torbrowser() {
    set -x
    cur_branch=`cat .git/HEAD | cut -d/ -f3`

    if [ "$#" = 0 ]; then
        echo "\"build + num\""
        return 0
    fi

    cur_branch_wo_prefix=`echo $cur_branch | cut -c 13-`
    FFVER=`echo $cur_branch_wo_prefix | cut -d- -f1`
    if [ -z "${FFVER}" ]; then
        echo "Specify firefox version (68.2.0)"
        return 1
    fi
    BUILD=$1
    if [ -z "${BUILD}" ]; then
        echo "Specify build number (build1)"
        return 1
    fi
    TBSERIES=`echo $cur_branch_wo_prefix | cut -d- -f2`
    if [ -z "${TBSERIES}" ]; then
        echo "Specify Tor Browser series (ex. 9.0)"
        return 1
    fi
    REBASE=`echo $cur_branch_wo_prefix | cut -d- -f3`
    if [ -z "${REBASE}" ]; then
        echo "Rebase number (ex. 1)"
        return 1
    fi
    REBASE_COMMENT=
    if [ "${REBASE}" -ne "1" ]; then
        REBASE_COMMENT=" (rebase ${REBASE})"
    fi

    BUILD=$1
    if [ -z "${BUILD}" ]; then
        echo "Specify build number (build1)"
        return 1
    fi

    CHANNEL=stable
    if `echo ${cur_branch} | grep -q \\\-11\.5`; then
        CHANNEL=alpha
    fi
    set +x
    git tag -s ${cur_branch}-${BUILD} -m "Tagging ${BUILD}${REBASE_COMMENT} for ${FFVER}-based ${CHANNEL}"
}
